export enum ACTION_TYPE {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  CLONE = 'CLONE',
  SUBMIT = 'SUBMIT',
  SUBMITTED = 'SUBMITTED',
  SUBMIT_FAILED = 'SUBMIT_FAILED',
  REGISTERED = 'REGISTERED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DELETE = 'DELETE',
}
